name= input("enter your name")
branch=input("enter your branch")
gender=input("enter your gender")
college=input("enter your college name")
age=input("enter your age")
print("Name",name)
print("Branch",branch)
print("Gender",gender)
print("College Name",college)
print("Age",age)
